### PR TITLE
Hello rails back-end

### PR DESCRIPTION
**Pull request by Loltolo-Lesapiti**
This project;

- Creates a new Rails API app.
- Initialize it with Git.
- Sets Postgres database.
- Create a table for storing your messages and create 5 different greetings.
- Create an API endpoint that selects a random greeting from the table.

Link to front-end: https://github.com/Loltolo-Lesapiti/hello-react-front-end

### CODE REVIEW

**Review by rloterh — COMMENTED** [review]
Hi Petro, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has incorrect gitflow/ GitHub flow. Kindly note that the Pull Request for this activity should flow **from feature into development**. Kindly use the correct gitflow and request another code review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by rloterh — COMMENTED** [review]
Hi Petro, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has incorrect gitflow/ GitHub flow. Kindly note that the Pull Request for this activity should flow **from feature into development**. Kindly use the correct gitflow and request another code review.

**Change the circled part:**
image

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Loltolo-Lesapiti** [comment]
I made the changes to flow from dev to main because of the previous review's feedback. I was on a call with a reviewer and he recommended that I follow the correct gitflow by creating a pull from dev to main branch. This was my preview review feedback: You have submitted a project, that has incorrect git flow for both the front-end and the back-end. kindly request to merge dev branch into main. @rloterh @Munsa1

**Comment by rloterh** [comment]
@Loltolo-Lesapiti 

At the moment I'm not informed of any changes regarding the Github flow/git-flow to the PR of this activity. In the meantime, I urge you to use the git-flow I mentioned above. I look forward to discussing this further with @Munsa1

**Comment by rloterh** [comment]
Hi Petro, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Kindly use a git-flow **from feature into development** for this activity. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request closed without merging**
